### PR TITLE
feat: Added dark mode to site

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
## Description
Added Dark mode feature to the site

## Linked Issues
Fixes : #25 

## Video 

https://github.com/undistro/cel-playground/assets/109150688/01f07b93-5b6d-455c-bea3-b91eb1738759

## How has this been tested?
- Click on the theme toggle button and change the mode

## Checklist
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by matheusfm** [comment]
Thank you for opening the PR, @pateldivyesh1323!
I appreciate your contribution.

Could you please consider implementing the persistence of the user's chosen theme?
Currently, it reverts to the default light theme upon page refresh, and having theme persistence would greatly enhance the user experience. One approach to achieve this could be using localStorage.
Sorry for not including this in the issue description.

We will also provide you with the color palette for the dark theme next Monday (October 9th), as soon as our Designer returns.

**Comment by matheusfm** [comment]
Hi @pateldivyesh1323,

We've prepared a Figma design with precise color details and improvements for our dark mode. You can access it here: https://www.figma.com/file/pasjtGKiZws9pkiVK9Gzp3/Playground?type=design&node-id=0-1&mode=design

Here are the key changes:

- Adjusted the shade of purple.
- For dark mode, textareas should use the `Tomorrow Night` Ace theme.
- The output textarea should be a disabled Ace editor to ensure we can use the `Tomorrow Night` theme in `text` mode. 
- Please ensure that the user's chosen theme (dark or light) persists, as discussed in the previous comment.

You can interact with the Figma prototype here: https://www.figma.com/proto/pasjtGKiZws9pkiVK9Gzp3/Playground?type=design&node-id=29-836&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=29%3A836&hide-ui=1

Could you please implement these changes?

Thank you for your patience.

**Comment by matheusfm** [comment]
Hi @marcelloale 
Thank you for this PR! I appreciate your contribution.


Could you please include the other fields in the input data of the example?

I see that you've included only `response.code` and `xds.cluster_name`, but there are several other fields documented [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes).

**Comment by pateldivyesh1323** [comment]
@matheusfm I am confused with 
- The Output text area, as it currently does not use ace-editor, and implementing ace-editor on it breaks 
some things. 
- Also I want to ask, should text color of input text areas should be changed as shown in figma?

**Comment by matheusfm** [comment]
@pateldivyesh1323 
If using ace-editor on the output textarea doesn't work, you can try setting the same background color to match the 'tomorrow night' theme.

**Comment by pateldivyesh1323** [comment]
@matheusfm ok, I will do that.

**Comment by pateldivyesh1323** [comment]
@matheusfm Updated.

image

**Comment by matheusfm** [comment]
Awesome, @pateldivyesh1323!
Thank you very much for your contribution and collaboration.
We really appreciate it.

**Comment by monuelo** [comment]
Impressive, guys! @matheusfm @pateldivyesh1323

**Pull request merged**
