### PR TITLE
fix: Add copy button in input fields

### LINKED ISSUE #24: Copy button for input fields
## Feature Description
Propose adding a copy button for both the **expression** and **input data** fields in the CEL Playground.

## Is this feature request related to a problem?
No

## What alternatives have been considered?
An alternative solution could be implementing an icon button on top of the fields. Use [phospor-icons](https://phosphoricons.com/) for consistency.

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
## Description
Add copy button on hover in text area

Fixes #24 

### Video

https://github.com/undistro/cel-playground/assets/109150688/b1d6ab40-7efe-43a1-ae49-f3b29c4f3e19

## Checklist
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by joaovictor3g** [comment]
Hi @pateldivyesh1323 I was testing your changes and I got those errors. They happen because the `Clipboard API` only works in secure context as this [article](https://bobbyhadz.com/blog/navigator-clipboard-is-undefined-in-javascript) says, probably in production environment it will work properly. Even though, as a suggestion in development environment a fallback can be provided to make clear why the copy is not working.

cel

**Comment by pateldivyesh1323** [comment]
Hi @joaovictor3g can you tell me how to reproduce it or how you tested it, and more about fallback which you are suggesting.

**Comment by joaovictor3g** [comment]
Hi @pateldivyesh1323 i tested in local environment running `make serve`, i am using chrome but the error behavior happened in firefox too. Basically the Clipboard API does not work outside HTTPS certificate. And about the fallback a simple `console.error` must sole it.

**Comment by pateldivyesh1323** [comment]
@joaovictor3g 
```
   navigator.clipboard.writeText(value).catch(console.error);
```
like this?

yes it does not usually work on http, but I cant reproduce it although I am using chrome

**Comment by joaovictor3g** [comment]
@pateldivyesh1323 yes, like that, can you please commit it?

**Comment by pateldivyesh1323** [comment]
@joaovictor3g Done.

**Comment by joaovictor3g** [comment]
@pateldivyesh1323 thank you very much for your contribution and collaboration.
We really appreciate it.

**Pull request merged**
