### PR TITLE
feat: add istio example (#29)

### PR DESCRIPTION
**Pull request by marcelloale**
## Description
Add Istio example access log filtering using CEL

## Linked Issues
#29

### CODE REVIEW

**Comment by matheusfm** [comment]
Hi @marcelloale 
Thank you for this PR! I appreciate your contribution.

Could you please include the other fields in the input data of the example?

I see that you've included only `response.code` and `xds.cluster_name`, but there are several other fields documented [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes).

**Comment by marcelloale** [comment]
> Hi, @marcelloale
> 
> Here are some examples of Istio/Envoy attributes for CEL: https://gist.github.com/matheusfm/31e96d49159937266e5bb88d69fddb91
> 
> This gist contains three YAML-formatted examples, where `client-passthrough-http.yml` seems to be related to the CEL expression you are adding, as `xds.cluster_name` is `PassthroughCluster`.
> 
> Could you please consider using this example as input data?
> 
> PS: A big thank you to @howardjohn for their help with these examples.

Hi @matheusfm ,

I've been occupied over the past week, but I intend to make the necessary adjustments as soon as possible this weekend.

I want to thank @matheusfm  and @howardjohn for the examples.

**Comment by marcelloale** [comment]
Hi @matheusfm, I've added the new input data, but I removed some 'null' fields to reduce the size of the example. If necessary, I can commit the original example without any alterations.

**Comment by matheusfm** [comment]
Thank you @marcelloale for the collaboration!

Could you resolve git conflicts please? Then we can merge these changes.

**Comment by marcelloale** [comment]
@matheusfm done

**Comment by matheusfm** [comment]
Thank you very much @marcelloale for your contribution and collaboration. We really appreciate it.

**Pull request merged**
